joint_names: ['spine_v0_axis0','spine_v0_axis1','spine_v0_axis2','spine_v1_axis0','spine_v1_axis1','spine_v1_axis2','spine_v2_axis0','spine_v2_axis1','spine_v2_axis2','sphere_head_axis0', 'sphere_head_axis1', 'sphere_head_axis2',
                  'sphere_left_axis0', 'sphere_left_axis1', 'sphere_left_axis2', 'elbow_left_rot0', 'elbow_left_rot1',
                  'sphere_right_axis0', 'sphere_right_axis1', 'sphere_right_axis2', 'elbow_right_rot0', 'elbow_right_rot1']
endeffectors: ['head','lower_arm_left', 'lower_arm_right']
head:
  base_link: 'base'
  joints: ['spine_v0_axis0','spine_v0_axis1','spine_v0_axis2','spine_v1_axis0','spine_v1_axis1','spine_v1_axis2','spine_v2_axis0','spine_v2_axis1','spine_v2_axis2','sphere_head_axis0', 'sphere_head_axis1', 'sphere_head_axis2']
lower_arm_left:
  base_link: 'base'
  joints: ['sphere_left_axis0', 'sphere_left_axis1', 'sphere_left_axis2', 'elbow_left_rot0', 'elbow_left_rot1']
lower_arm_right:
  base_link: 'base'
  joints: ['sphere_right_axis0', 'sphere_right_axis1', 'sphere_right_axis2', 'elbow_right_rot0', 'elbow_right_rot1']