joint_names: ['joint0', 'joint1', 'joint2', 'sphere_axis0', 'sphere_axis1', 'sphere_axis2']
endeffectors: ['theClaw']
theClaw:
  base_link: 'base'
  joints: ['joint0', 'joint1', 'joint2', 'sphere_axis0', 'sphere_axis1', 'sphere_axis2']