#  These controllers are loaded by the robot.launch script, the following types are available
#  type: cardsflow/kindyn/TorquePositionController
#  type: cardsflow/kindyn/CableLengthController
#  type: cardsflow/kindyn/CableLengthVelocityController
#  type: cardsflow/kindyn/ForcePositionController
rikshaw__joint_hip_left:
  joint: rikshaw__joint_hip_left
  type: cardsflow/kindyn/CableLengthController
rikshaw__joint_hip_right:
  joint: rikshaw__joint_hip_right
  type: cardsflow/kindyn/CableLengthController
rikshaw__joint_knee_left:
  joint: rikshaw__joint_knee_left
  type: cardsflow/kindyn/CableLengthController
rikshaw__joint_knee_right:
  joint: rikshaw__joint_knee_right
  type: cardsflow/kindyn/CableLengthController
rikshaw__joint_foot_left:
  joint: rikshaw__joint_foot_left
  type: cardsflow/kindyn/CableLengthController
rikshaw__joint_foot_right:
  joint: rikshaw__joint_foot_right
  type: cardsflow/kindyn/CableLengthController

rikshaw__left_shoulder_axis0:
  joint: rikshaw__left_shoulder_axis0
  type: cardsflow/kindyn/CableLengthController
rikshaw__left_shoulder_axis1:
  joint: rikshaw__left_shoulder_axis1
  type: cardsflow/kindyn/CableLengthController
rikshaw__left_shoulder_axis2:
  joint: rikshaw__left_shoulder_axis2
  type: cardsflow/kindyn/CableLengthController
rikshaw__elbow_left:
  joint: rikshaw__elbow_left_rot0
  type: cardsflow/kindyn/CableLengthController
rikshaw__wrist_left_sphere_axis0:
  joint: rikshaw__wrist_left_sphere_axis0
  type: cardsflow/kindyn/CableLengthController
rikshaw__wrist_left_sphere_axis1:
  joint: rikshaw__wrist_left_sphere_axis1
  type: cardsflow/kindyn/CableLengthController
rikshaw__wrist_left_sphere_axis2:
  joint: rikshaw__wrist_left_sphere_axis2
  type: cardsflow/kindyn/CableLengthController

rikshaw__right_shoulder_axis0:
  joint: rikshaw__right_shoulder_axis0
  type: cardsflow/kindyn/CableLengthController
rikshaw__right_shoulder_axis1:
  joint: rikshaw__right_shoulder_axis1
  type: cardsflow/kindyn/CableLengthController
rikshaw__right_shoulder_axis2:
  joint: rikshaw__right_shoulder_axis2
  type: cardsflow/kindyn/CableLengthController
rikshaw__elbow_right:
  joint: rikshaw__elbow_right
  type: cardsflow/kindyn/CableLengthController
rikshaw__wrist_right_sphere_axis0:
  joint: rikshaw__wrist_right_sphere_axis0
  type: cardsflow/kindyn/CableLengthController
rikshaw__wrist_right_sphere_axis1:
  joint: rikshaw__wrist_right_sphere_axis1
  type: cardsflow/kindyn/CableLengthController
rikshaw__wrist_right_sphere_axis2:
  joint: rikshaw__wrist_right_sphere_axis2
  type: cardsflow/kindyn/CableLengthController

rikshaw__little_right_joint0:
  joint: rikshaw__little_right_joint0
  type: cardsflow/kindyn/TorquePositionController
rikshaw__ring_right_joint0:
  joint: rikshaw__ring_right_joint0
  type: cardsflow/kindyn/TorquePositionController
rikshaw__middle_right_joint0:
  joint: rikshaw__middle_right_joint0
  type: cardsflow/kindyn/TorquePositionController
rikshaw__index_right_joint0:
  joint: rikshaw__index_right_joint0
  type: cardsflow/kindyn/TorquePositionController
rikshaw__thumb_right_joint0:
  joint: rikshaw__thumb_right_joint0
  type: cardsflow/kindyn/TorquePositionController
rikshaw__little_right_joint1:
  joint: rikshaw__little_right_joint1
  type: cardsflow/kindyn/TorquePositionController
rikshaw__ring_right_joint1:
  joint: rikshaw__ring_right_joint1
  type: cardsflow/kindyn/TorquePositionController
rikshaw__middle_right_joint1:
  joint: rikshaw__middle_right_joint1
  type: cardsflow/kindyn/TorquePositionController
rikshaw__index_right_joint1:
  joint: rikshaw__index_right_joint1
  type: cardsflow/kindyn/TorquePositionController
rikshaw__thumb_right_joint1:
  joint: rikshaw__thumb_right_joint1
  type: cardsflow/kindyn/TorquePositionController
rikshaw__little_right_joint2:
  joint: rikshaw__little_right_joint2
  type: cardsflow/kindyn/TorquePositionController
rikshaw__ring_right_joint2:
  joint: rikshaw__ring_right_joint2
  type: cardsflow/kindyn/TorquePositionController
rikshaw__middle_right_joint2:
  joint: rikshaw__middle_right_joint2
  type: cardsflow/kindyn/TorquePositionController
rikshaw__index_right_joint2:
  joint: rikshaw__index_right_joint2
  type: cardsflow/kindyn/TorquePositionController
rikshaw__thumb_right_joint2:
  joint: rikshaw__thumb_right_joint2
  type: cardsflow/kindyn/TorquePositionController

rikshaw__little_left_joint0:
  joint: rikshaw__little_left_joint0
  type: cardsflow/kindyn/TorquePositionController
rikshaw__ring_left_joint0:
  joint: rikshaw__ring_left_joint0
  type: cardsflow/kindyn/TorquePositionController
rikshaw__middle_left_joint0:
  joint: rikshaw__middle_left_joint0
  type: cardsflow/kindyn/TorquePositionController
rikshaw__index_left_joint0:
  joint: rikshaw__index_left_joint0
  type: cardsflow/kindyn/TorquePositionController
rikshaw__thumb_left_joint0:
  joint: rikshaw__thumb_left_joint0
  type: cardsflow/kindyn/TorquePositionController
rikshaw__little_left_joint1:
  joint: rikshaw__little_left_joint1
  type: cardsflow/kindyn/TorquePositionController
rikshaw__ring_left_joint1:
  joint: rikshaw__ring_left_joint1
  type: cardsflow/kindyn/TorquePositionController
rikshaw__middle_left_joint1:
  joint: rikshaw__middle_left_joint1
  type: cardsflow/kindyn/TorquePositionController
rikshaw__index_left_joint1:
  joint: rikshaw__index_left_joint1
  type: cardsflow/kindyn/TorquePositionController
rikshaw__thumb_left_joint1:
  joint: rikshaw__thumb_left_joint1
  type: cardsflow/kindyn/TorquePositionController
rikshaw__little_left_joint2:
  joint: rikshaw__little_left_joint2
  type: cardsflow/kindyn/TorquePositionController
rikshaw__ring_left_joint2:
  joint: rikshaw__ring_left_joint2
  type: cardsflow/kindyn/TorquePositionController
rikshaw__middle_left_joint2:
  joint: rikshaw__middle_left_joint2
  type: cardsflow/kindyn/TorquePositionController
rikshaw__index_left_joint2:
  joint: rikshaw__index_left_joint2
  type: cardsflow/kindyn/TorquePositionController
rikshaw__thumb_left_joint2:
  joint: rikshaw__thumb_left_joint2
  type: cardsflow/kindyn/TorquePositionController

rikshaw__spine_joint:
  joint: spine_joint
  type: cardsflow/kindyn/CableLengthController
rikshaw__sphere_head_axis0:
  joint: rikshaw__sphere_head_axis0
  type: cardsflow/kindyn/CableLengthController
rikshaw__sphere_head_axis1:
  joint: rikshaw__sphere_head_axis1
  type: cardsflow/kindyn/CableLengthController
rikshaw__sphere_head_axis2:
  joint: rikshaw__sphere_head_axis2
  type: cardsflow/kindyn/CableLengthController


rikshjoint_wheel_right:
  joint: rikshaw__joint_wheel_right
  type: cardsflow/kindyn/TorquePositionController
rikshaw__joint_wheel_back:
  joint: rikshaw__joint_wheel_back
  type: cardsflow/kindyn/TorquePositionController
rikshaw__joint_pedal:
  joint: rikshaw__joint_pedal
  type: cardsflow/kindyn/TorquePositionController
rikshaw__joint_wheel_left:
  joint: rikshaw__joint_wheel_left
  type: cardsflow/kindyn/TorquePositionController
rikshaw__joint_front:
  joint: rikshaw__joint_front
  type: cardsflow/kindyn/CableLengthController
rikshaw__joint_pedal_right:
  joint: rikshaw__joint_pedal_right
  type: cardsflow/kindyn/TorquePositionController
rikshaw__joint_wheel_back:
  joint: rikshaw__joint_wheel_back
  type: cardsflow/kindyn/TorquePositionController
rikshaw__joint_pedal_left:
  joint: rikshaw__joint_pedal_left
  type: cardsflow/kindyn/TorquePositionController
