#  These controllers are loaded by the robot.launch script, the following types are available
#  type: cardsflow/kindyn/TorquePositionController
#  type: cardsflow/kindyn/CableLengthController
#  type: cardsflow/kindyn/CableLengthVelocityController
#  type: cardsflow/kindyn/ForcePositionController
joint_hip_left:
  joint: joint_hip_left
  type: cardsflow/kindyn/CableLengthController
joint_hip_right:
  joint: joint_hip_right
  type: cardsflow/kindyn/CableLengthController
joint_knee_left:
  joint: joint_knee_left
  type: cardsflow/kindyn/CableLengthController
joint_knee_right:
  joint: joint_knee_right
  type: cardsflow/kindyn/CableLengthController
joint_foot_left:
  joint: joint_foot_left
  type: cardsflow/kindyn/CableLengthController
joint_foot_right:
  joint: joint_foot_right
  type: cardsflow/kindyn/CableLengthController

left_shoulder_axis0:
  joint: left_shoulder_axis0
  type: cardsflow/kindyn/CableLengthController
left_shoulder_axis1:
  joint: left_shoulder_axis1
  type: cardsflow/kindyn/CableLengthController
left_shoulder_axis2:
  joint: left_shoulder_axis2
  type: cardsflow/kindyn/CableLengthController
elbow_left:
  joint: elbow_left
  type: cardsflow/kindyn/CableLengthController
wrist_left_sphere_axis0:
  joint: wrist_left_sphere_axis0
  type: cardsflow/kindyn/CableLengthController
wrist_left_sphere_axis1:
  joint: wrist_left_sphere_axis1
  type: cardsflow/kindyn/CableLengthController
wrist_left_sphere_axis2:
  joint: wrist_left_sphere_axis2
  type: cardsflow/kindyn/CableLengthController

right_shoulder_axis0:
  joint: right_shoulder_axis0
  type: cardsflow/kindyn/CableLengthController
right_shoulder_axis1:
  joint: right_shoulder_axis1
  type: cardsflow/kindyn/CableLengthController
right_shoulder_axis2:
  joint: right_shoulder_axis2
  type: cardsflow/kindyn/CableLengthController
elbow_right:
  joint: elbow_right
  type: cardsflow/kindyn/CableLengthController
wrist_right_sphere_axis0:
  joint: wrist_right_sphere_axis0
  type: cardsflow/kindyn/CableLengthController
wrist_right_sphere_axis1:
  joint: wrist_right_sphere_axis1
  type: cardsflow/kindyn/CableLengthController
wrist_right_sphere_axis2:
  joint: wrist_right_sphere_axis2
  type: cardsflow/kindyn/CableLengthController

little_right_joint0:
  joint: little_right_joint0
  type: cardsflow/kindyn/TorquePositionController
ring_right_joint0:
  joint: ring_right_joint0
  type: cardsflow/kindyn/TorquePositionController
middle_right_joint0:
  joint: middle_right_joint0
  type: cardsflow/kindyn/TorquePositionController
index_right_joint0:
  joint: index_right_joint0
  type: cardsflow/kindyn/TorquePositionController
thumb_right_joint0:
  joint: thumb_right_joint0
  type: cardsflow/kindyn/TorquePositionController
little_right_joint1:
  joint: little_right_joint1
  type: cardsflow/kindyn/TorquePositionController
ring_right_joint1:
  joint: ring_right_joint1
  type: cardsflow/kindyn/TorquePositionController
middle_right_joint1:
  joint: middle_right_joint1
  type: cardsflow/kindyn/TorquePositionController
index_right_joint1:
  joint: index_right_joint1
  type: cardsflow/kindyn/TorquePositionController
thumb_right_joint1:
  joint: thumb_right_joint1
  type: cardsflow/kindyn/TorquePositionController
little_right_joint2:
  joint: little_right_joint2
  type: cardsflow/kindyn/TorquePositionController
ring_right_joint2:
  joint: ring_right_joint2
  type: cardsflow/kindyn/TorquePositionController
middle_right_joint2:
  joint: middle_right_joint2
  type: cardsflow/kindyn/TorquePositionController
index_right_joint2:
  joint: index_right_joint2
  type: cardsflow/kindyn/TorquePositionController
thumb_right_joint2:
  joint: thumb_right_joint2
  type: cardsflow/kindyn/TorquePositionController

little_left_joint0:
  joint: little_left_joint0
  type: cardsflow/kindyn/TorquePositionController
ring_left_joint0:
  joint: ring_left_joint0
  type: cardsflow/kindyn/TorquePositionController
middle_left_joint0:
  joint: middle_left_joint0
  type: cardsflow/kindyn/TorquePositionController
index_left_joint0:
  joint: index_left_joint0
  type: cardsflow/kindyn/TorquePositionController
thumb_left_joint0:
  joint: thumb_left_joint0
  type: cardsflow/kindyn/TorquePositionController
little_left_joint1:
  joint: little_left_joint1
  type: cardsflow/kindyn/TorquePositionController
ring_left_joint1:
  joint: ring_left_joint1
  type: cardsflow/kindyn/TorquePositionController
middle_left_joint1:
  joint: middle_left_joint1
  type: cardsflow/kindyn/TorquePositionController
index_left_joint1:
  joint: index_left_joint1
  type: cardsflow/kindyn/TorquePositionController
thumb_left_joint1:
  joint: thumb_left_joint1
  type: cardsflow/kindyn/TorquePositionController
little_left_joint2:
  joint: little_left_joint2
  type: cardsflow/kindyn/TorquePositionController
ring_left_joint2:
  joint: ring_left_joint2
  type: cardsflow/kindyn/TorquePositionController
middle_left_joint2:
  joint: middle_left_joint2
  type: cardsflow/kindyn/TorquePositionController
index_left_joint2:
  joint: index_left_joint2
  type: cardsflow/kindyn/TorquePositionController
thumb_left_joint2:
  joint: thumb_left_joint2
  type: cardsflow/kindyn/TorquePositionController

spine_joint:
  joint: spine_joint
  type: cardsflow/kindyn/CableLengthController
sphere_head_axis0:
  joint: sphere_head_axis0
  type: cardsflow/kindyn/CableLengthController
sphere_head_axis1:
  joint: sphere_head_axis1
  type: cardsflow/kindyn/CableLengthController
sphere_head_axis2:
  joint: sphere_head_axis2
  type: cardsflow/kindyn/CableLengthController


joint_wheel_right:
  joint: joint_wheel_right
  type: cardsflow/kindyn/TorquePositionController
joint_wheel_back:
  joint: joint_wheel_back
  type: cardsflow/kindyn/TorquePositionController
joint_pedal:
  joint: joint_pedal
  type: cardsflow/kindyn/TorquePositionController
joint_wheel_left:
  joint: joint_wheel_left
  type: cardsflow/kindyn/TorquePositionController
joint_front:
  joint: joint_front
  type: cardsflow/kindyn/CableLengthController
joint_pedal_right:
  joint: joint_pedal_right
  type: cardsflow/kindyn/TorquePositionController
joint_wheel_back:
  joint: joint_wheel_back
  type: cardsflow/kindyn/TorquePositionController
joint_pedal_left:
  joint: joint_pedal_left
  type: cardsflow/kindyn/TorquePositionController
