joint_names: ['spine_joint', 'head_axis0', 'head_axis1', 'head_axis2',
'joint_hip_left', 'joint_knee_left', 'joint_foot_left', 'joint_foot_left_tip',
'joint_hip_right', 'joint_knee_right', 'joint_foot_right', 'joint_foot_right_tip',
'left_shoulder_axis0', 'left_shoulder_axis1', 'left_shoulder_axis2', 'elbow_left_rot0', 'elbow_left_rot1', 'left_wrist_0', 'left_wrist_1',
'right_shoulder_axis0', 'right_shoulder_axis1', 'right_shoulder_axis2', 'elbow_right_rot0', 'elbow_right_rot1', 'right_wrist_0', 'right_wrist_1',
'joint_front','joint_wheel_left','joint_wheel_right','joint_wheel_back','joint_pedal','joint_pedal_right','joint_pedal_left']
endeffectors: ['head','foot_left_tip','foot_right_tip','left_hand','right_hand','bike']
head:
  base_link: 'bike'
  joints: ['spine_joint', 'head_axis0', 'head_axis1', 'head_axis2']
foot_left_tip:
  base_link: 'bike'
  joints: ['joint_hip_left', 'joint_knee_left', 'joint_foot_left', 'joint_foot_left_tip']
foot_right_tip:
  base_link: 'bike'
  joints: ['joint_hip_right', 'joint_knee_right', 'joint_foot_right', 'joint_foot_right_tip']
left_hand:
  base_link: 'bike'
  joints: ['left_shoulder_axis0', 'left_shoulder_axis1', 'left_shoulder_axis2', 'elbow_left_rot0', 'elbow_left_rot1', 'left_wrist_0', 'left_wrist_1']
right_hand:
  base_link: 'bike'
  joints: ['right_shoulder_axis0', 'right_shoulder_axis1', 'right_shoulder_axis2', 'elbow_right_rot0', 'elbow_right_rot1', 'right_wrist_0', 'right_wrist_1']
bike:
  base_link: 'bike'
  joints: ['joint_front','joint_wheel_left','joint_wheel_right','joint_wheel_back','joint_pedal','joint_pedal_right','joint_pedal_left']