joint_names: ['spine_joint', 'sphere_head_axis0', 'sphere_head_axis1', 'sphere_head_axis2',
'joint_hip_left', 'joint_knee_left', 'joint_foot_left', 'joint_foot_left_tip',
'joint_hip_right', 'joint_knee_right', 'joint_foot_right', 'joint_foot_right_tip',
'left_shoulder_axis0', 'left_shoulder_axis1', 'left_shoulder_axis2', 'elbow_left', 'wrist_left_sphere_axis0', 'wrist_left_sphere_axis1', 'wrist_left_sphere_axis2',
'right_shoulder_axis0', 'right_shoulder_axis1', 'right_shoulder_axis2', 'elbow_right', 'wrist_right_sphere_axis0', 'wrist_right_sphere_axis1', 'wrist_right_sphere_axis2', 'little_right_joint0', 'ring_right_joint0', 'middle_right_joint0', 'index_right_joint0', 'thumb_right_joint0', 'little_right_joint1', 'ring_right_joint1', 'middle_right_joint1', 'index_right_joint1', 'thumb_right_joint1', 'little_right_joint2', 'ring_right_joint2', 'middle_right_joint2', 'index_right_joint2', 'thumb_right_joint2',
'little_left_joint0', 'ring_left_joint0', 'middle_left_joint0', 'index_left_joint0', 'thumb_left_joint0', 'little_left_joint1', 'ring_left_joint1', 'middle_left_joint1', 'index_left_joint1', 'thumb_left_joint1', 'little_left_joint2', 'ring_left_joint2', 'middle_left_joint2', 'index_left_joint2', 'thumb_left_joint2',
'joint_wheel_left','joint_wheel_right','joint_front',
'joint_wheel_back','joint_pedal','joint_pedal_right',
'joint_pedal_left']
endeffectors: ['left_leg','right_leg','left_arm','right_arm', 'head']
left_arm:
  base_link: 'bike'
  joints: ['left_shoulder_axis0', 'left_shoulder_axis1', 'left_shoulder_axis2', 'elbow_left', wrist_left_sphere_axis0, wrist_left_sphere_axis1, wrist_left_sphere_axis2, 'little_left_joint0', 'ring_left_joint0', 'middle_left_joint0', 'index_left_joint0', 'thumb_left_joint0', 'little_left_joint1', 'ring_left_joint1', 'middle_left_joint1', 'index_left_joint1', 'thumb_left_joint1', 'little_left_joint2', 'ring_left_joint2', 'middle_left_joint2', 'index_left_joint2', 'thumb_left_joint2']
right_arm:
  base_link: 'bike'
  joints: ['right_shoulder_axis0', 'right_shoulder_axis1', 'right_shoulder_axis2', 'elbow_right', 'wrist_right_sphere_axis0', 'wrist_right_sphere_axis1', 'wrist_right_sphere_axis2', 'little_right_joint0', 'ring_right_joint0', 'middle_right_joint0', 'index_right_joint0', 'thumb_right_joint0', 'little_right_joint1', 'ring_right_joint1', 'middle_right_joint1', 'index_right_joint1', 'thumb_right_joint1', 'little_right_joint2', 'ring_right_joint2', 'middle_right_joint2', 'index_right_joint2', 'thumb_right_joint2']
left_leg:
  base_link: 'bike'
  joints: ['joint_hip_left', 'joint_knee_left', 'joint_foot_left', 'joint_foot_left_tip']
right_leg:
  base_link: 'bike'
  joints: ['joint_hip_right', 'joint_knee_right', 'joint_foot_right', 'joint_foot_right_tip']
head:
  base_link: 'bike'
  joints: ['spine_joint', 'sphere_head_axis0', 'sphere_head_axis1', 'sphere_head_axis2']
