sphere_axis0:
  joint: sphere_axis0
  type: cardsflow/kindyn/TorquePositionController
#  type: cardsflow/kindyn/TorquePositionController
sphere_axis1:
  joint: sphere_axis1
  type: cardsflow/kindyn/CableLengthController
sphere_axis2:
  joint: sphere_axis2
  type: cardsflow/kindyn/TorquePositionController