#  These controllers are loaded by the robot.launch script, the following types are available
#  type: cardsflow/kindyn/TorquePositionController
#  type: cardsflow/kindyn/CableLengthController
#  type: cardsflow/kindyn/ForcePositionController
joint0:
  joint: joint0
  type: cardsflow/kindyn/CableLengthController
joint1:
  joint: joint1
  type: cardsflow/kindyn/CableLengthController
joint2:
  joint: joint2
  type: cardsflow/kindyn/CableLengthController