joint_names: ['hip_joint','sphere_head_axis0', 'sphere_head_axis1', 'sphere_head_axis2',
                  'sphere_left_axis0', 'sphere_left_axis1', 'sphere_left_axis2', 'elbow_left_rot0', 'elbow_left_rot1', 'left_wrist_0', 'left_wrist_1',
                  'sphere_right_axis0', 'sphere_right_axis1', 'sphere_right_axis2', 'elbow_right_rot0', 'elbow_right_rot1', 'right_wrist_0', 'right_wrist_1']
endeffectors: ['head','left_hand', 'right_hand']
head:
  base_link: 'base'
  joints: ['hip_joint','sphere_head_axis0', 'sphere_head_axis1', 'sphere_head_axis2']
left_hand:
  base_link: 'torso'
  joints: ['sphere_left_axis0', 'sphere_left_axis1', 'sphere_left_axis2', 'elbow_left_rot0', 'elbow_left_rot1', 'left_wrist_0', 'left_wrist_1']
right_hand:
  base_link: 'torso'
  joints: ['sphere_right_axis0', 'sphere_right_axis1', 'sphere_right_axis2', 'elbow_right_rot0', 'elbow_right_rot1', 'right_wrist_0', 'right_wrist_1']