#  These controllers are loaded by the robot.launch script, the following types are available
#  type: cardsflow/kindyn/TorquePositionController
#  type: cardsflow/kindyn/CableLengthController
#  type: cardsflow/kindyn/CableLengthVelocityController
#  type: cardsflow/kindyn/ForcePositionController
#   roslaunch kindyn robot.launch robot_name:=VRpuppet start_controllers:='motor0 motor1 motor2 motor3 motor4 motor5 motor6 motor7 motor8 motor9 motor10 motor11 motor12 motor13'

shoulder_left_axis0:
  joint: shoulder_left_axis0
  type: cardsflow/kindyn/ForcePositionController
shoulder_left_axis1:
  joint: shoulder_left_axis1
  type: cardsflow/kindyn/ForcePositionController
shoulder_left_axis2:
  joint: shoulder_left_axis2
  type: cardsflow/kindyn/ForcePositionController
elbow_left_axis0:
  joint: elbow_left_axis0
  type: cardsflow/kindyn/ForcePositionController
elbow_left_axis1:
  joint: elbow_left_axis1
  type: cardsflow/kindyn/ForcePositionController
elbow_left_axis2:
  joint: elbow_left_axis2
  type: cardsflow/kindyn/ForcePositionController
wrist_left_axis0:
  joint: wrist_left_axis0
  type: cardsflow/kindyn/ForcePositionController
wrist_left_axis1:
  joint: wrist_left_axis1
  type: cardsflow/kindyn/ForcePositionController
wrist_left_axis2:
  joint: wrist_left_axis2
  type: cardsflow/kindyn/ForcePositionController

motor0:
  joint: motor0
  type: cardsflow/kindyn/ForcePositionController
motor1:
  joint: motor1
  type: cardsflow/kindyn/ForcePositionController
motor2:
  joint: motor2
  type: cardsflow/kindyn/ForcePositionController
motor3:
  joint: motor3
  type: cardsflow/kindyn/ForcePositionController
motor4:
  joint: motor4
  type: cardsflow/kindyn/ForcePositionController
motor5:
  joint: motor5
  type: cardsflow/kindyn/ForcePositionController
motor6:
  joint: motor6
  type: cardsflow/kindyn/ForcePositionController
motor7:
  joint: motor7
  type: cardsflow/kindyn/ForcePositionController
motor8:
  joint: motor8
  type: cardsflow/kindyn/ForcePositionController
motor9:
  joint: motor9
  type: cardsflow/kindyn/ForcePositionController
motor10:
  joint: motor10
  type: cardsflow/kindyn/ForcePositionController
motor11:
  joint: motor11
  type: cardsflow/kindyn/ForcePositionController
motor12:
  joint: motor12
  type: cardsflow/kindyn/ForcePositionController
motor13:
  joint: motor13
  type: cardsflow/kindyn/ForcePositionController