#  These controllers are loaded by the robot.launch script, the following types are available
#  type: cardsflow/kindyn/TorquePositionController
#  type: cardsflow/kindyn/CableLengthController
#  type: cardsflow/kindyn/CableLengthVelocityController
#  type: cardsflow/kindyn/ForcePositionController
axis0:
  joint: axis0
  type: cardsflow/kindyn/CableLengthController
axis1:
  joint: axis1
  type: cardsflow/kindyn/CableLengthController
axis2:
  joint: axis2
  type: cardsflow/kindyn/CableLengthController
axis3:
  joint: axis3
  type: cardsflow/kindyn/CableLengthController
axis4:
  joint: axis4
  type: cardsflow/kindyn/CableLengthController
axis5:
  joint: axis5
  type: cardsflow/kindyn/CableLengthController
motor0:
  joint: motor0
  type: cardsflow/kindyn/CableLengthController
motor1:
  joint: motor1
  type: cardsflow/kindyn/CableLengthController
motor2:
  joint: motor2
  type: cardsflow/kindyn/CableLengthController
motor3:
  joint: motor3
  type: cardsflow/kindyn/CableLengthController
motor4:
  joint: motor4
  type: cardsflow/kindyn/CableLengthController
motor5:
  joint: motor5
  type: cardsflow/kindyn/CableLengthController