#  These controllers are loaded by the robot.launch script, the following types are available
#  type: cardsflow/kindyn/TorquePositionController
#  type: cardsflow/kindyn/CableLengthController
#  type: cardsflow/kindyn/CableLengthVelocityController
#  type: cardsflow/kindyn/ForcePositionController
6dof_axis0:
  joint: 6dof_axis0
  type: cardsflow/kindyn/CableLengthController
6dof_axis1:
  joint: 6dof_axis1
  type: cardsflow/kindyn/CableLengthController
6dof_axis2:
  joint: 6dof_axis2
  type: cardsflow/kindyn/CableLengthController
6dof_axis3:
  joint: 6dof_axis3
  type: cardsflow/kindyn/CableLengthController
6dof_axis4:
  joint: 6dof_axis4
  type: cardsflow/kindyn/CableLengthController
6dof_axis5:
  joint: 6dof_axis5
  type: cardsflow/kindyn/CableLengthController