joint_names: [ 'motor0','motor1','motor2','motor3','motor4','motor5','motor6','motor7','motor8','motor9','motor10','motor11','motor12','motor13',
              'shoulder_left_axis0','shoulder_left_axis1','shoulder_left_axis2',
               'elbow_left_axis0','elbow_left_axis1','elbow_left_axis2',
               'wrist_left_axis0','wrist_left_axis1','wrist_left_axis2']
endeffectors: ['hand_left']
hand_left:
  base_link: 'base'
  joints: [ 'motor0','motor1','motor2','motor3','motor4','motor5','motor6','motor7','motor8','motor9','motor10','motor11','motor12','motor13',
            'shoulder_left_axis0','shoulder_left_axis1','shoulder_left_axis2',
            'elbow_left_axis0','elbow_left_axis1','elbow_left_axis2',
            'wrist_left_axis0','wrist_left_axis1','wrist_left_axis2' ]