joint_names: ['motor0', 'motor1', 'motor2', 'motor3', 'motor4', 'motor5', 'axis0', 'axis1', 'axis2', 'axis3', 'axis4', 'axis5']
endeffectors: ['top']
top:
  base_link: 'base'
  joints: ['axis0', 'axis1', 'axis2', 'axis3', 'axis4', 'axis5']