head:
  bodyPartID: 4
  init_mode: 'DIRECT_PWM'
  init_setpoint: 250
  real_motor_ids: [9,10,11,12,13,14]
  sim_motor_ids: [20,19,18,23,22,21]
  motor_type: [2,1,1,1,1,2]
  board_name: 'shoulder_right'
  use_motor_config: true
shoulder_left:
  bodyPartID: 3
  init_mode: 'DISPLACEMENT'
  init_setpoint: 20
  real_motor_ids: [0,1,2,3,4,5,6,7,8]
  sim_motor_ids: [9,10,11,12,13,14,15,16,17]
  motor_type: [0,0,0,0,0,0,0,0,0]
  board_name: 'shoulder_left'
  use_motor_config: true
shoulder_right:
  bodyPartID: 4
  init_mode: 'DISPLACEMENT'
  init_setpoint: 20
  real_motor_ids: [0,1,2,3,4,5,6,7,8]
  sim_motor_ids: [0,1,2,3,4,5,6,7,8]
  motor_type: [0,0,0,0,0,0,0,0,0]
  board_name: 'shoulder_right'
  use_motor_config: true
arm_left:
  bodyPartID: 5
  init_mode: 'DIRECT_PWM'
  init_setpoint: 100
  real_motor_ids: [0, 1]
  sim_motor_ids: [26, 27]
  motor_type: [2, 2]
  board_name: 'arm_left'
  use_motor_config: false
arm_right:
  bodyPartID: 6
  init_mode: 'DIRECT_PWM'
  init_setpoint: 180
  real_motor_ids: [0, 1]
  sim_motor_ids: [25, 24]
  motor_type: [1, 1]
  board_name: 'arm_right'
  use_motor_config: false
